services:
  stats-service:
    build:
      context: ./stats/stats-client
      dockerfile: Dockerfile
    image: explore-stats-service
    container_name: stats-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://server:9090

  stats-server:
      build:
        context: ./stats/stats-server
        dockerfile: Dockerfile
#      image: stats-server
      container_name: stats-server
      ports:
        - "9090:9090"
      depends_on:
        - stats-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stats_db
        - SPRING_DATASOURCE_USERNAME=dbuser
        - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=stats_db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:16.1
